name: plannotate
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - plannotate
  - selenium
  - pip
  - pip:
    - Bio==1.8.0
    - biopython==1.85
    - streamlit==1.47.0
prefix: /home/zippy/anaconda3/envs/plannotate
