name: plannotate
channels:
  - conda-forge
  - defaults #added to see if solving is sped up
  #- bioconda
dependencies:
  - click
  - curl
  - numpy
  - biopython>=1.78
  - blast>=2.10.1
  - diamond>=2.0.13
  - pandas>=1.3.5,<2.0.0
  - python>=3.9
  - ripgrep>=13.0.0
  - tabulate>=0.8.9
  - trnascan-se>=2.0.7
  - streamlit=1.8.1
  - altair=4.2.*
  - bokeh=2.4.1
  - protobuf=3.20.*

# name: plannotate
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   - python
#   - biopython>=1.78
#   - plannotate
#   - selenium
#   - pip
#   - pip:
#     - biopython
#     - streamlit
# prefix: /home/zippy/anaconda3/envs/plannotate
#ctrl+/ to comment out in bulk
