name: plannotate
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - biopython
  - plannotate
  - selenium
  - pip
  - pip:
    - biopython
    - streamlit
prefix: /home/zippy/anaconda3/envs/plannotate
